### ISSUE TITLE
Add the ability to test the connection without printing

### ISSUE THREAD

**Issue by ryall** [receiptline/receiptio#2]
I would like to be able to test that the printer is online, without actually printing anything.

**Comment by receiptline** [comment]
Thanks for using ReceiptIO!

Try running it with the `-q` option.

```
$ receiptio -d 192.168.192.168 -p escpos -q
```

If the printer is online, it will return 'online' (exit code: 100).

**Comment by ryall** [comment]
Awesome, thank you!
